//! Test fixtures for the Base block proving types.
//!
//! Unlike the rest of this crate, this module is NOT expected to come from
//! base/base: it is PoC-local synthetic data for tests and the
//! `tvc_base_cli` demo flow, gated behind the `fixtures` feature.
//!
//! # How the fixture was produced
//!
//! The example is a fully synthetic single-block chain, chosen so the real
//! stateless executor can run it offline with no captured network data:
//!
//! - The parent block (#41) commits to the **empty state trie**
//!   (`EMPTY_ROOT_HASH`), so the pre-state needs no witness trie nodes —
//!   the executor's `TrieNode` handles the empty root natively.
//! - The rollup config is [`RollupConfig::default()`] with only Regolith
//!   active from genesis: no Canyon/Ecotone/Holocene header rules apply,
//!   which keeps the synthetic header self-consistent.
//! - Block #42 contains a single deposit transaction (the only Base
//!   transaction type that needs no signature) minting 1 ETH to the
//!   sender, so execution touches state and produces a non-empty
//!   post-state root.
//! - [`EXAMPLE_BLOCK_HASH`] and the claimed commitments were generated by
//!   running [`crate::prover::prove_block`] once over this witness and
//!   pinning the resulting header hash; the tests then act as regression
//!   checks that re-execution keeps reproducing it.
//!
//! Against a real network the witness would instead be captured from a
//! Base node via the `debug_executionWitness` RPC plus the block's header
//! and raw transactions.

use alloy_consensus::{EMPTY_ROOT_HASH, Header};
use alloy_eips::eip2718::Encodable2718;
use alloy_primitives::{TxKind, keccak256};
use alloy_rlp::Encodable;
use base_common_consensus::TxDeposit;

use crate::{
    Address, B256, BasePayloadAttributes, BlockWitness, Bytes, ExecutionWitness, PublicInputs,
    RollupConfig, U256,
};

/// Block hash of the example block (#42), generated by a one-time run of
/// the stateless executor over [`example_witness`] and pinned here as a
/// regression constant.
pub const EXAMPLE_BLOCK_HASH: B256 = B256::new([
    0x5d, 0xb5, 0x97, 0x68, 0xd0, 0xc4, 0x6e, 0x9e, 0xba, 0x77, 0xab, 0x8d, 0x5a, 0xaa, 0xb0, 0x2d,
    0xd0, 0xde, 0xbb, 0xce, 0xe4, 0xbe, 0x4c, 0xc3, 0xfb, 0x08, 0x55, 0x92, 0xa5, 0xc6, 0x82, 0x8b,
]);

/// Sender of the example deposit (and beneficiary of the example block).
const DEPOSIT_SENDER: Address = Address::repeat_byte(0x5e);

/// EIP-2718 encoding of the example deposit transaction with the given
/// mint amount (wei). The fixture uses 1 ETH; tests use other values to
/// tamper with the block.
#[must_use]
pub fn example_deposit_tx_with_mint(mint: u128) -> Bytes {
    let deposit = TxDeposit {
        source_hash: B256::repeat_byte(0x01),
        from: DEPOSIT_SENDER,
        to: TxKind::Call(Address::repeat_byte(0xba)),
        mint,
        value: U256::ZERO,
        gas_limit: 100_000,
        is_system_transaction: false,
        input: Bytes::new(),
    };
    deposit.encoded_2718().into()
}

/// Build a well-formed synthetic [`BlockWitness`] for local testing: one
/// Base L2 block (#42) with a single 1-ETH-mint deposit transaction on top
/// of an empty-state parent (#41), consistent with the checks performed by
/// [`crate::prover::prove_block`]. See the module docs for how it was
/// produced.
#[must_use]
pub fn example_witness() -> BlockWitness {
    // Rollup config: defaults (no upgrades scheduled) with Regolith active
    // from genesis for sane deposit gas accounting.
    let mut rollup_config = RollupConfig::default();
    rollup_config.upgrades.regolith_time = Some(0);

    // Parent block #41 committing to the empty state trie.
    let parent_header = Header {
        number: 41,
        timestamp: 1_000,
        gas_limit: 30_000_000,
        base_fee_per_gas: Some(1_000_000),
        state_root: EMPTY_ROOT_HASH,
        ..Header::default()
    };
    let mut parent_header_rlp = Vec::new();
    parent_header.encode(&mut parent_header_rlp);
    let parent_block_hash = keccak256(&parent_header_rlp);

    // Payload attributes reconstructed from block #42.
    let mut attributes = BasePayloadAttributes::default();
    attributes.payload_attributes.timestamp = 1_002;
    attributes.payload_attributes.prev_randao = B256::repeat_byte(0x42);
    attributes.payload_attributes.suggested_fee_recipient = DEPOSIT_SENDER;
    attributes.transactions = Some(vec![example_deposit_tx_with_mint(
        1_000_000_000_000_000_000,
    )]);
    attributes.no_tx_pool = Some(true);
    attributes.gas_limit = Some(30_000_000);

    // Pre-state witness: the empty state trie needs no nodes; only the
    // parent header preimage is carried (for BLOCKHASH-style lookups).
    let execution_witness = ExecutionWitness {
        state: Vec::new(),
        codes: Vec::new(),
        keys: Vec::new(),
        headers: vec![parent_header_rlp.clone().into()],
    };

    BlockWitness {
        public_inputs: PublicInputs {
            parent_block_hash,
            block_number: 42,
            claimed_block_hash: EXAMPLE_BLOCK_HASH,
        },
        rollup_config,
        parent_header_rlp: parent_header_rlp.into(),
        attributes,
        execution_witness,
    }
}
